version: '3.7'

services:
  php:
    container_name: php
    image: php:8.0-fpm
    volumes:
      - ./app:/var/www/html

  nginx:
    container_name: nginx
    depends_on:
      - php
    image: nginx:1.13
    ports:
      - 81:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/html
